---
title: "Day 01"
author: "Lizzie"
date: "2022-12-01"
knit: resrepo::knit_to_results
output:
  github_document:
    toc: yes
    toc_depth: 4
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Day 1: calorie counting

### Part 1

Aim: read the data, each elf is separated by a blank line, sum the numbers for each elf and find the one that's carrying the most calories.

```{r part-1}

## read data from file
c <- readLines("../data/day_01_1.txt")
head(c, n=10)

## make a df to store the sum for each elf
df <- data.frame(n_elf = numeric(), n_cal = numeric())
t_elf <- 1
t_cal <- 0
for (i in 1:length(c)) {
  if (c[i] != "") {
    t_cal <- t_cal + as.numeric(c[i])
  } else if (c[i] == "") {
    row <- data.frame(n_elf = t_elf, n_cal = t_cal)
    df <- rbind(df, row) # add to df
    t_elf <- t_elf + 1 # next elf
    t_cal <- 0  # reset
  }
}

head(df)

## find the elf carrying the most calories - how many?
max(df$n_cal)

```


### Part 2

How many calories are the top three elves (by number of calories) carrying?

```{r part-2}

## sort in reverse order of n_cal
df <- df[order(-df$n_cal), ]
head(df)

## sum first three n_cal
sum(df$n_cal[1:3])
```


End.



